---
title: "Trends in Subscription Seat Changes"
author: "SaewonPark"
date: "June 2, 2020"
output: 
  html_document: 
    keep_md: yes
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse)
```

 <br>

### Build a dummy dataset
```{r}

set.seed(12)

dummy <- expand.grid(c("Plus","Pro"),
                  seq(1:12),
                  c(2019,2020),
                  c("Gaming", "Education", "Construction", "Film")) %>%
  rename("productName" = 1,
         "month" = 2,
         "year" = 3,
         "industry" = 4) %>%
  mutate(lostSeats = runif(nrow(.), min = 0, max = 100)) %>%
  filter(!(year == 2020 & month > 5) &
           productName == "Pro")



```

<br>

### Plot the Seat Count Trends


We want to see:

  - The impact of the new pricing model implemented this year
  - The impact of the global lockdown
  - How the impacts vary depending on the customer's industry (The current health crisis has varying levels of impact depending on the industry)
  

<br>

```{r fig.height=6, fig.width=8, fig.align='center'}

ggplot(aes(x = month,
           y = lostSeats,
           color = as.factor(year)),
       data = dummy) +
  geom_line() +
  geom_vline(xintercept = 3,
             color = "red") +
  annotate(geom = "text", 
           x = 4.7,
           y = 20, 
           size = 2,
           label="Global lockdown begins",
           color="red") +
  theme_bw() +
  scale_x_continuous(breaks = seq(1:12)) +
  facet_wrap(~ industry) +
  labs(title = "Seat Count Trends by Industry",
       y = "Seat Count",
       x = "Month",
       color = "Year") +
  scale_color_brewer(palette = "Paired")




```

<br>
<br>